# Generated by Django 4.0.3 on 2022-04-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс')),
            ],
        ),
    ]
